name: jal_setu
description: A Flutter utility service portal UI (MGX Jal Setu style) using MVC + GetX.
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.19.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

